import uuid
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Response
from pydantic import BaseModel
from sqlalchemy.orm import Session

from ..auth import get_current_user, require_role
from ..database import get_db
from ..models import ExcludedNumber, User

router = APIRouter(prefix="/excluded-phone-numbers", tags=["excluded numbers"])


class ExcludedNumberCreate(BaseModel):
    number: str
    reason: Optional[str] = None


@router.get("")
def list_excluded_numbers(db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    items = db.query(ExcludedNumber).filter(ExcludedNumber.organization_id == user.organization_id).order_by(ExcludedNumber.created_at.desc()).all()
    return {"items": [{"id": item.id, "number": item.number, "reason": item.reason, "added_by_id": item.added_by_id, "date": item.created_at} for item in items], "total": len(items)}


@router.post("", status_code=201)
def create_excluded_number(body: ExcludedNumberCreate, db: Session = Depends(get_db), user: User = Depends(require_role("ADMIN"))):
    exists = db.query(ExcludedNumber).filter(ExcludedNumber.organization_id == user.organization_id, ExcludedNumber.number == body.number).first()
    if exists:
        raise HTTPException(status_code=409, detail="This number is already excluded")
    # id is auto-generated by DB trigger
    item = ExcludedNumber(organization_id=user.organization_id, added_by_id=user.id, **body.model_dump())
    db.add(item)
    db.commit()
    db.refresh(item)
    return {"id": item.id, "number": item.number, "reason": item.reason, "date": item.created_at}


@router.delete("/{number_id}", status_code=204)
def delete_excluded_number(number_id: str, db: Session = Depends(get_db), user: User = Depends(require_role("ADMIN"))):
    item = db.query(ExcludedNumber).filter(ExcludedNumber.id == number_id, ExcludedNumber.organization_id == user.organization_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Excluded number not found")
    db.delete(item)
    db.commit()
    return Response(status_code=204)
